ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/AddGoal.cshtml.cs
using GoalManager.Core.GoalManagement;
using System.ComponentModel.DataAnnotations;

using GoalManager.UseCases.GoalManagement.AddGoal;
using GoalManager.UseCases.GoalManagement.GetGoalTypeLookup;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using GoalManager.UseCases.GoalManagement.GetGoalValueTypeLookup;

namespace GoalManager.Web.Pages.GoalManagement;

[Authorize]
public class AddGoalModel(IMediator mediator) : PageModelBase
{
  [BindProperty]
  [Required(ErrorMessage = "Goal Title is required.")]
  public string Title { get; set; } = null!;

  [BindProperty]
  [Required(ErrorMessage = "Goal Type is required.")]
  public int? GoalTypeId { get; set; }

  [BindProperty]
  [Required(ErrorMessage = "Goal Value Type is required.")]
  public int? GoalValueTypeId { get; set; }

  [BindProperty]
  [Required(ErrorMessage = "Min Value is required.")]
  [Range(0, int.MaxValue, ErrorMessage = "Min Value must be a non-negative integer.")]
  public int MinValue { get; set; }

  [BindProperty]
  [Required(ErrorMessage = "Mid Value is required.")]
  [Range(0, int.MaxValue, ErrorMessage = "Mid Value must be a non-negative integer.")]
  public int MidValue { get; set; }

  [BindProperty]
  [Required(ErrorMessage = "Max Value is required.")]
  [Range(0, int.MaxValue, ErrorMessage = "Max Value must be a non-negative integer.")]
  public int MaxValue { get; set; }

  [BindProperty]
  [Required(ErrorMessage = "Percentage is required.")]
  [Range(0, int.MaxValue, ErrorMessage = "Percentage must be a non-negative integer.")]
  public int Percentage { get; set; }

  public List<SelectListItem> GoalTypeOptions { get; set; } = new();
  public List<SelectListItem> GoalValueTypeOptions { get; set; } = new();

  public async Task<IActionResult> OnGetAsync()
  {
    var goalTypesResult = await mediator.Send(new GetGoalTypeLookupQuery()).ConfigureAwait(false);

    AddResultMessages(goalTypesResult);

    if (goalTypesResult.IsSuccess)
    {
      var goalTypes = goalTypesResult.Value.Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();
      //GoalTypeOptions.Add(new SelectListItem("Choose..", string.Empty));
      GoalTypeOptions.AddRange(goalTypes);
    }

    var goalValueTypesResult = await mediator.Send(new GetGoalValueTypeLookupQuery()).ConfigureAwait(false);

    AddResultMessages(goalValueTypesResult);

    if (goalValueTypesResult.IsSuccess)
    {
      var goalValueTypes = goalValueTypesResult.Value.Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();
      //GoalValueTypeOptions.Add(new SelectListItem("Choose..", string.Empty));
      GoalValueTypeOptions.AddRange(goalValueTypes);
    }

    return Page();
  }

  public async Task<IActionResult> OnPostAsync(int goalSetId)
  {
    if (!ModelState.IsValid)
    {
      return await OnGetAsync().ConfigureAwait(false);
    }

    var result = await mediator.Send(
                   new AddGoalCommand(
                     goalSetId,
                     Title,
                     GoalType.FromValue(GoalTypeId.GetValueOrDefault()),
                     MinValue,
                     MidValue,
                     MaxValue,
                     GoalValueType.FromValue(GoalValueTypeId.GetValueOrDefault()),
                     Percentage));
    
    AddResultMessages(result);

    if (!result.IsSuccess)
    {
      return await OnGetAsync().ConfigureAwait(false);
    }

    return RedirectToPageWithSuccessMessage("TeamGoals", new { result.Value.TeamId }, "Goal is Added");
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/AddGoalPeriod.cshtml.cs
using GoalManager.UseCases.GoalManagement.AddGoalPeriod;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.GoalManagement;

[Authorize]
public class AddGoalPeriodModel(IMediator mediator) : PageModelBase
{
  public async Task<IActionResult> OnGetAsync(int teamId)
  {
    var result = await mediator.Send(new AddGoalPeriodCommand(teamId, 0, DateTime.Now.Year));

    AddResultMessages(result);

    return Page();
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/ApproveTeamGoals.cshtml.cs
using GoalManager.UseCases.GoalManagement.ApproveGoalSet;
using GoalManager.UseCases.GoalManagement.GetGoalSet;
using GoalManager.UseCases.GoalManagement.RejectGoalSet;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.GoalManagement;

[Authorize]
public class ApproveTeamGoalsModel(IMediator mediator) : PageModelBase
{
  public int Year { get; private set; }

  public GoalSetDto? GoalSet { get; private set; }

  public async Task<IActionResult> OnGetAsync(int teamId, int userId)
  {
    var year = DateTime.Now.Year;

    Year = year;

    var goalSetResult = await mediator.Send(new GetGoalSetQuery(teamId, year, userId)).ConfigureAwait(false);
    if (goalSetResult.IsSuccess)
    {
      GoalSet = goalSetResult.Value;
    }

    AddResultMessages(goalSetResult);

    return Page();
  }

  public async Task<IActionResult> OnPostApproveAsync(int teamId, int userId, int goalSetId)
  {
    var user = HttpContext.GetUserContext();
    var result = await mediator.Send(new ApproveGoalSetCommand(goalSetId, user.Id)).ConfigureAwait(false);

    AddResultMessages(result);

    return await OnGetAsync(teamId, userId).ConfigureAwait(false);
  }

  public async Task<IActionResult> OnPostRejectAsync(int teamId, int userId, int goalSetId)
  {
    var user = HttpContext.GetUserContext();
    var result = await mediator.Send(new RejectGoalSetCommand(goalSetId, user.Id)).ConfigureAwait(false);

    AddResultMessages(result);

    return await OnGetAsync(teamId, userId).ConfigureAwait(false);
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/Goals.cshtml.cs
using GoalManager.UseCases.Organisation.ListUserTeams;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.GoalManagement;

[Authorize]
public class ListTeamsModel(IMediator mediator) : PageModelBase
{
  public List<UserTeamListItemDto> Teams { get; private set; } = new();

  public int Year { get; private set; }

  public async Task<IActionResult> OnGetAsync()
  {
    var user = HttpContext.GetUserContext();
   
    Teams = await mediator.Send(new ListUserTeamsQuery(user.Id));
    Year = DateTime.Today.Year;

    return Page();
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/PendingApprovals.cshtml.cs
using GoalManager.UseCases.GoalManagement.ApproveGoalProgress;
using GoalManager.UseCases.GoalManagement.GetPendingApprovalGoals;
using GoalManager.UseCases.GoalManagement.GetPendingApprovalGoalSets;
using GoalManager.UseCases.GoalManagement.RejectGoalProgress;
using GoalManager.Web.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.GoalManagement;

[Authorize]
public class PendingGoalsModel(IMediator mediator) : PageModelBase
{
  public List<PendingApprovalGoalDto> PendingGoals { get; private set; } = [];

  public List<PendingApprovalGoalSetDto> PendingGoalSets { get; private set; } = [];

  public async Task<IActionResult> OnGetAsync()
  {
    var user = HttpContext.GetUserContext();

    PendingGoals = await mediator.Send(new GetPendingApprovalGoalsQuery(user.Id)).ConfigureAwait(false);
    PendingGoalSets = await mediator.Send(new GetPendingApprovalGoalSetsQuery(user.Id)).ConfigureAwait(false);

    return Page();
  }

  public async Task<IActionResult> OnPostApproveAsync(int goalSetId, int goalId)
  {
    var command = new ApproveGoalProgressCommand(goalSetId, goalId);

    var result = await mediator.Send(command);

    if (result.IsSuccess)
    {
      SuccessMessages.Add("Goal approved successfully");
    }
    else
    {
      ErrorMessages.Add("Couldnt Update");
    }

    return RedirectToPage();
  }

  public async Task<IActionResult> OnPostRejectAsync(int goalSetId, int goalId)
  {
    var command = new RejectGoalProgressCommand(goalSetId, goalId);

    var result = await mediator.Send(command);

    if (result.IsSuccess)
    {
      SuccessMessages.Add("Goal rejected");
    }
    else
    {
      ErrorMessages.Add("Couldnt Update");
    }

    return RedirectToPage();
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/TeamGoals.cshtml.cs
using GoalManager.UseCases.GoalManagement.CreateGoalSet;
using GoalManager.UseCases.GoalManagement.GetGoalSet;
using GoalManager.UseCases.GoalManagement.SendGoalSetToApproval;
using GoalManager.UseCases.GoalManagement.UpdateGoalProgress;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.GoalManagement;

[Authorize]
public class TeamGoalsModel(IMediator mediator) : PageModelBase
{
  public int Year { get; private set; }
  public GoalSetDto? GoalSet { get; private set; }
  public async Task<IActionResult> OnGetAsync(int teamId)
  {
    var year = DateTime.Now.Year;
    var user = HttpContext.GetUserContext();

    Year = year;

    var goalSetResult = await mediator.Send(new GetGoalSetQuery(teamId, year, user.Id)).ConfigureAwait(false);
    if (goalSetResult.IsSuccess)
    {
      if (goalSetResult.Value == null)
      {
        var createGoalSetResult = await mediator.Send(new CreateGoalSetCommand(teamId, year, user.Id));
        if (!createGoalSetResult.IsSuccess)
        {
          AddResultMessages(createGoalSetResult);
          return Page();
        }

        goalSetResult = await mediator.Send(new GetGoalSetQuery(teamId, year, user.Id)).ConfigureAwait(false);
      }

      GoalSet = goalSetResult.Value;
    }

    AddResultMessages(goalSetResult);

    return Page();
  }

  public async Task<IActionResult> OnPostUpdateProgressAsync(
      int teamId,
      int goalSetId,
      int goalId,
      int actualValue,
      string comment)
  {
    var result = await mediator.Send(new UpdateGoalProgressCommand(
        GoalSetId: goalSetId,
        GoalId: goalId,
        ActualValue: actualValue,
        Comment: comment
    )).ConfigureAwait(false);

    AddResultMessages(result);

    return await OnGetAsync(teamId).ConfigureAwait(false);
  }

  public async Task<IActionResult> OnPostSendToApprovalAsync(int teamId, int goalSetId)
  {
    var result = await mediator.Send(new SendGoalSetToApprovalCommand(goalSetId)).ConfigureAwait(false);

    AddResultMessages(result);

    return await OnGetAsync(teamId).ConfigureAwait(false);
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/UpdateGoal.cshtml.cs
using System.ComponentModel.DataAnnotations;
using GoalManager.Core.GoalManagement;
using GoalManager.UseCases.GoalManagement.GetGoal;
using GoalManager.UseCases.GoalManagement.GetGoalTypeLookup;
using GoalManager.UseCases.GoalManagement.GetGoalValueTypeLookup;
using GoalManager.UseCases.GoalManagement.UpdateGoal;
using GoalManager.Web.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GoalManager.Web.Pages.GoalManagement;

[Authorize]
public class UpdateGoalModel(IMediator mediator) : PageModelBase
{
  [BindProperty]
  [Required(ErrorMessage = "Goal Title is required.")]
  public string Title { get; set; } = null!;

  [BindProperty]
  [Required(ErrorMessage = "Goal Type is required.")]
  public int? GoalTypeId { get; set; }

  [BindProperty]
  [Required(ErrorMessage = "Goal Value Type is required.")]
  public int? GoalValueTypeId { get; set; }

  [BindProperty]
  [Required(ErrorMessage = "Percentage is required.")]
  [Range(0, int.MaxValue, ErrorMessage = "Percentage must be a non-negative integer.")]
  public int Percentage { get; set; }

  public List<SelectListItem> GoalTypeOptions { get; set; } = new();
  public List<SelectListItem> GoalValueTypeOptions { get; set; } = new();


  public async Task<IActionResult> OnGetAsync(int goalSetId, int goalId)
  {
    var goalResult = await mediator.Send(new GetGoalQuery(goalSetId, goalId)).ConfigureAwait(false);

    AddResultMessages(goalResult);

    if (goalResult.IsSuccess)
    {
      Title = goalResult.Value.Title;
      Percentage = goalResult.Value.Percentage;
      GoalValueTypeId = goalResult.Value.GoalValue.GoalValueType.Value;
      GoalTypeId = goalResult.Value.GoalType.Value;
    }

    var goalTypesResult = await mediator.Send(new GetGoalTypeLookupQuery()).ConfigureAwait(false);

    AddResultMessages(goalTypesResult);

    if (goalTypesResult.IsSuccess)
    {
      var goalTypes = goalTypesResult.Value.Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();
      //GoalTypeOptions.Add(new SelectListItem("Choose..", string.Empty));
      GoalTypeOptions.AddRange(goalTypes);
    }

    var goalValueTypesResult = await mediator.Send(new GetGoalValueTypeLookupQuery()).ConfigureAwait(false);

    AddResultMessages(goalValueTypesResult);

    if (goalValueTypesResult.IsSuccess)
    {
      var goalValueTypes = goalValueTypesResult.Value.Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();
      //GoalValueTypeOptions.Add(new SelectListItem("Choose..", string.Empty));
      GoalValueTypeOptions.AddRange(goalValueTypes);
    }

    return Page();
  }

  public async Task<IActionResult> OnPostAsync(int goalSetId, int goalId)
  {
    if (!ModelState.IsValid)
    {
      return await OnGetAsync(goalSetId, goalId).ConfigureAwait(false);
    }

    var result = await mediator.Send(
                   new UpdateGoalCommand(
                     goalSetId,
                     goalId,
                     Title,
                     GoalType.FromValue(GoalTypeId.GetValueOrDefault()),
                     GoalValueType.FromValue(GoalValueTypeId.GetValueOrDefault()),
                     Percentage));

    AddResultMessages(result);

    if (!result.IsSuccess)
    {
      return await OnGetAsync(goalSetId, goalId).ConfigureAwait(false);
    }

    return RedirectToPageWithSuccessMessage("UpdateGoal", new { result.Value.GoalSetId, result.Value.GoalId }, "Goal is updated");
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/AddGoalPeriod.cshtml
@page "{teamId:int}"
@model GoalManager.Web.Pages.GoalManagement.AddGoalPeriodModel
@{
	ViewData["Title"] = "Add Goal Period";
}

<div class="container py-4">
	<div class="text-center mb-4">
		<h1 class="h4 fw-light">Add Goal Period</h1>
	</div>

	<alert-messages error-messages="Model.ErrorMessages" success-messages="Model.SuccessMessages"></alert-messages>
</div>

<style>
	.container {
		max-width: 800px;
	}

	.fw-light {
		font-weight: 300;
	}
</style>

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/ApproveTeamGoals.cshtml
@page "{teamId:int}/{userId:int}"
@using GoalManager.Core.GoalManagement
@model GoalManager.Web.Pages.GoalManagement.ApproveTeamGoalsModel

@{
    ViewData["Title"] = $"{Model.GoalSet?.TeamName} {Model.Year} Goals";
}

<div class="container py-4">
    <h1 class="h3 fw-normal mb-3">Team Member: @Model.GoalSet?.User</h1>
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div class="d-flex justify-content-between align-items-center">
            <h2 class="h3 fw-light mb-1">@Model.GoalSet?.TeamName @Model.Year Goals</h2>
        </div>
        @if (Model.GoalSet?.Status == GoalSetStatus.Approved)
        {
            <div class="status-badge status-approved mt-2">
                <i class="fas fa-check-circle"></i> Approved
            </div>
        }
        else if (Model.GoalSet?.Status == GoalSetStatus.WaitingForApproval)
        {
            <div class="status-badge status-waiting mt-2">
                <i class="fas fa-clock"></i> Waiting For Approval
            </div>
        }
    </div>

    <alert-messages error-messages="Model.ErrorMessages" success-messages="Model.SuccessMessages"></alert-messages>

    @if (Model.GoalSet != null)
    {
        <div class="mb-4">
            @foreach (var goal in Model.GoalSet.Goals)
            {
                var latestStatus = goal.Status;
                var latestStatusText = latestStatus?.ToString() ?? "No Status";

                <div class="card mb-3">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-start mb-3">
                            <div class="text-decoration-none text-reset w-100">
                                <div class="d-flex justify-content-between align-items-start mb-3">
                                    <h5 class="mb-1 fw-normal">@goal.Title</h5>
                                    <div class="d-flex align-items-center gap-2">
                                        <span class="badge @GetBadgeStyle(latestStatusText)">
                                            @latestStatusText
                                        </span>
                                        <span class="badge bg-light text-dark">@goal.GoalType.Name</span>
                                    </div>
                                </div>
                                <div class="row g-3 mb-3">
                                    <div class="col-md-3">
                                        <div class="text-muted small">Percentage</div>
                                        <div>@goal.Percentage%</div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="text-muted small">Value Type</div>
                                        <div>@goal.GoalValue.GoalValueType.Name</div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="text-muted small">Min</div>
                                        <div>@goal.GoalValue.MinValue</div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="text-muted small">Mid</div>
                                        <div>@goal.GoalValue.MidValue</div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="text-muted small">Max</div>
                                        <div>@goal.GoalValue.MaxValue</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row g-3 align-items-end">
                            <div class="col-md-6">
                                <label class="form-label small text-muted">Current Progress</label>
                                <div class="d-flex align-items-center gap-3">
                                    @goal.ActualValue
                                </div>
                            </div>

                            <div class="col-md-5">
                                <label class="form-label small text-muted">Comment</label>
                                <div class="d-flex align-items-center gap-3">
                                    @(string.IsNullOrWhiteSpace(goal.Comment) ? Html.Raw("&nbsp;") : goal.Comment)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        @if (Model.GoalSet.Status == GoalSetStatus.WaitingForApproval)
        {
            <div class="d-flex justify-content-end gap-2">
                <form method="post" asp-page-handler="Approve"
                      asp-route-teamId="@Model.GoalSet.TeamId"
                      asp-route-userId="@Model.GoalSet.UserId">
                    <input type="hidden" name="goalSetId" value="@Model.GoalSet.Id" />
                    <button type="submit" class="btn btn-sm btn-success">
                        <i class="fas fa-check"></i> Approve
                    </button>
                </form>
                <form method="post" asp-page-handler="Reject"
                      asp-route-teamId="@Model.GoalSet.TeamId"
                      asp-route-userId="@Model.GoalSet.UserId">
                    <input type="hidden" name="goalSetId" value="@Model.GoalSet.Id" />
                    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to reject?')">
                        <i class="fas fa-times"></i> Reject
                    </button>
                </form>
            </div>
        }
    }
</div>

@functions {
    public static string GetBadgeStyle(string status)
    {
        return status switch
            {
                "WaitingForApproval" => "bg-warning text-dark",
                "Approved" => "bg-success text-white",
                "Rejected" => "bg-danger text-white",
                _ => "bg-secondary text-white" // default case for unknown statuses
            };
    }
}

@section Style
{
    <style>
		.card {
		    border: 1px solid #e9ecef;
		    border-radius: 0.5rem;
		    box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
		    transition: transform 0.2s ease-in-out;
		}

        .card-body {
            padding: 1.5rem;
        }

		.card:hover {
		    transform: translateY(-2px);
		    box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.1);
		}

		.card-body {
		    padding: 1.5rem;
		}

		a[asp-page="UpdateGoal"] {
		    position: relative;
		    z-index: 1;
		}

        .status-badge {
            font-size: 1rem;
            padding: 0.5rem 1rem;
            border-radius: 0.5rem;
            font-weight: 500;
            display: inline-flex;
            align-items: center;
            gap: 0.5rem;
        }

        .status-badge i {
            font-size: 1.1rem;
        }

        .status-approved {
            background-color: #198754;
            color: white;
        }

        .status-waiting {
            background-color: #ffc107;
            color: #212529;
        }
	</style>
}

ddd/goal-management-system/src/GoalManager.Web/Pages/GoalManagement/PendingApprovals.cshtml
@page
@model GoalManager.Web.Pages.GoalManagement.PendingGoalsModel
@{
	ViewData["Title"] = "Pending Approvals";
}

<div class="container py-4">
    <alert-messages error-messages="Model.ErrorMessages" success-messages="Model.SuccessMessages"></alert-messages>

    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h1 class="h3 fw-light mb-0">Pending Goals for Approval</h1>
        </div>
    </div>

    @if (!Model.PendingGoals.Any())
    {
        <div class="card border-0 shadow-sm text-center py-5">
            <i class="fas fa-tasks fa-3x text-muted mb-3"></i>
            <h3 class="h5 fw-normal">No pending goals</h3>
            <p class="text-muted mb-4">There are currently no goals awaiting approval.</p>
        </div>
    }
    else
    {
        <div class="card border-0 shadow-sm">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead class="bg-light">
                    <tr>
                        <th class="border-0">Team</th>
                        <th class="border-0">Goal Title</th>
                        <th class="border-0">User</th>
                        <th class="border-0 text-center">Progress</th>
                        <th class="border-0">Comment</th>
                        <th class="border-0 text-end">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var goal in Model.PendingGoals)
                    {
                        <tr>
                            <td class="align-middle">
                                <span class="badge bg-light text-dark">@goal.TeamName</span>
                            </td>
                            <td class="align-middle">
                                <div class="text-truncate" style="max-width: 200px;" title="@goal.GoalTitle">
                                    @goal.GoalTitle
                                </div>
                            </td>
                            <td class="align-middle">
                                <small class="text-muted">@goal.User</small>
                            </td>
                            <td class="align-middle text-center">
                                <div class="d-flex align-items-center gap-2">
                                    <span>@goal.ActualValue</span>
                                    <div class="progress flex-grow-1" style="height: 6px;">
                                        <div class="progress-bar bg-warning"
                                             style="width: @CalculatePercentage(goal.MinValue, goal.MaxValue, goal.ActualValue)%"></div>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">
                                <div class="text-truncate" style="max-width: 150px;" title="@goal.Comment">
                                    @(string.IsNullOrEmpty(goal.Comment) ? "-" : goal.Comment)
                                </div>
                            </td>
                            <td class="align-middle text-end">
                                <div class="d-flex justify-content-end gap-2">
                                    <form asp-page-handler="Approve" method="post">
                                        <input type="hidden" name="goalSetId" value="@goal.GoalSetId"/>
                                        <input type="hidden" name="goalId" value="@goal.GoalId"/>
                                        <button type="submit" class="btn btn-sm btn-outline-success">
                                            <i class="fas fa-check"></i> Approve
                                        </button>
                                    </form>
                                    <form asp-page-handler="Reject" method="post">
                                        <input type="hidden" name="goalSetId" value="@goal.GoalSetId"/>
                                        <input type="hidden" name="goalId" value="@goal.GoalId"/>
                                        <button type="submit" class="btn btn-sm btn-outline-danger"
                                                onclick="return confirm('Reject this goal?')">
                                            <i class="fas fa-times"></i> Reject
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    }

    <br/>
    <hr/>
    <br/>
    
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h1 class="h3 fw-light mb-0">Pending Goal Sets for Approval</h1>
        </div>
    </div>

    @if (!Model.PendingGoalSets.Any())
    {
        <div class="card border-0 shadow-sm text-center py-5">
            <i class="fas fa-tasks fa-3x text-muted mb-3"></i>
            <h3 class="h5 fw-normal">No pending goal sets</h3>
            <p class="text-muted mb-4">There are currently no goal sets awaiting approval.</p>
        </div>
    }
    else
    {
        <div class="card border-0 shadow-sm">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead class="bg-light">
                    <tr>
                        <th class="border-0">Team</th>
                        <th class="border-0">User</th>
                        <th class="border-0 text-end">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var goalSet in Model.PendingGoalSets)
                    {
                        <tr>
                            <td class="align-middle">
                                <span class="badge bg-light text-dark">@goalSet.TeamName</span>
                            </td>
                            <td class="align-middle">
                                <small class="text-muted">@goalSet.User</small>
                            </td>
                            <td class="align-middle text-end">
                                <div class="d-flex justify-content-end gap-2">
                                    <a asp-page="ApproveTeamGoals" 
                                       asp-route-teamId="@goalSet.TeamId"
                                       asp-route-userId="@goalSet.UserId"
                                       class="btn btn-sm btn-outline-success">
                                        <i class="fas fa-check"></i> Approve / Reject
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    }
</div>

@functions {
	private static int CalculatePercentage(decimal min, decimal max, decimal actual)
	{
		if (max <= min) return 0;
		var percentage = (actual - min) / (max - min) * 100;
		return (int)Math.Clamp(percentage, 0, 100);
	}
}

@section Style
{
    <style>
        .text-truncate {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        .table td, .table th {
            vertical-align: middle;
        }

        .progress {
            min-width: 80px;
            background-color: #e9ecef;
        }

        .badge {
            padding: 0.35em 0.65em;
            font-size: 0.875em;
        }
    </style>
}