ddd/goal-management-system/src/GoalManager.Web/ViewModels/Organisation/CreateOrganisationViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GoalManager.Web.ViewModels.Organisation;

public class CreateOrganisationViewModel
{
  [Required]
  public string Name { get; set; } = null!;
}

ddd/goal-management-system/src/GoalManager.Web/ViewModels/Organisation/OrganisationListItemViewModel.cs
namespace GoalManager.Web.ViewModels.Organisation;

public record OrganisationListItemViewModel(int Id, string Name, int TeamsCount);

ddd/goal-management-system/src/GoalManager.Web/Pages/Notification/List.cshtml.cs
using GoalManager.UseCases.Notification.List;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.Notification;

[Authorize]
public class ListModel(IMediator mediator) : PageModelBase
{
  private const int PageSize = 10;

  public PagedResult<List<NotificationListItemDto>> NotificationsPagedResult { get; private set; } =
    new(new PagedInfo(1, PageSize, 0, 0), []);

  public async Task OnGetAsync([FromQuery] int? page, CancellationToken cancellationToken = default)
  {
    var result = await mediator.Send(new ListNotificationsQuery(page < 1 ? 1 : page.GetValueOrDefault(1), PageSize), cancellationToken).ConfigureAwait(false);
    AddResultMessages(result);
    NotificationsPagedResult = result;
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/AddMember.cshtml.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

using GoalManager.UseCases.Identity.GetUserLookup;
using GoalManager.UseCases.Organisation.AddTeamMember;
using GoalManager.UseCases.Organisation.GetTeamMemberTypeLookup;
using GoalManager.UseCases.Organisation.GetTeamName;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GoalManager.Web.Pages.Organisation;

[Authorize]
public class AddMemberModel(IMediator mediator) : PageModelBase
{
  public string? TeamName { get; set; }

  [DisplayName("User")]
  [Required]
  [BindProperty]
  public int? UserId { get; set; }

  [DisplayName("Member Type")]
  [Required]
  [BindProperty]
  public int? MemberTypeId { get; set; }

  public List<SelectListItem> Users { get; set; } = new(0);

  public List<SelectListItem> MemberTypes { get; set; } = new(0);

  public async Task<IActionResult> OnGetAsync(int teamId)
  {
    var teamNameResult = await mediator.Send(new GetTeamNameQuery(teamId)).ConfigureAwait(false);

    AddResultMessages(teamNameResult);

    if (teamNameResult.IsSuccess)
    {
      TeamName = teamNameResult.Value;
    }

    var usersResult = await mediator.Send(new GetUserLookupQuery()).ConfigureAwait(false);

    AddResultMessages(usersResult);

    if (usersResult.IsSuccess)
    {
      var users = usersResult.Value.Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();
      //Users.Add(new SelectListItem("Choose..", string.Empty));
      Users.AddRange(users);
    }

    var memberTypesResult = await mediator.Send(new GetTeamMemberTypeLookupQuery()).ConfigureAwait(false);

    AddResultMessages(memberTypesResult);

    if (memberTypesResult.IsSuccess)
    {
      var memberTypes = memberTypesResult.Value.Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();
      //MemberTypes.Add(new SelectListItem("Choose..", string.Empty));
      MemberTypes.AddRange(memberTypes);
    }

    return Page();
  }

  public async Task<IActionResult> OnPostAsync(int organisationId, int teamId)
  {
    if (!ModelState.IsValid)
    {
      return await OnGetAsync(teamId).ConfigureAwait(false);
    }

    var result = await mediator.Send(new AddTeamMemberCommand(organisationId, teamId, UserId.GetValueOrDefault(), MemberTypeId.GetValueOrDefault())).ConfigureAwait(false);

    AddResultMessages(result);

    if (!result.IsSuccess)
    {
      return await OnGetAsync(teamId).ConfigureAwait(false);
    }

    return RedirectToPageWithSuccessMessage("UpdateTeam", new {organisationId, teamId}, "Team Member is Added");
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/Create.cshtml.cs
using GoalManager.UseCases.Organisation.CreateOrganisation;
using GoalManager.Web.Common;
using GoalManager.Web.ViewModels.Organisation;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.Organisation;

[Authorize]
public class CreateModel(IMediator mediator) : PageModelBase
{
  [BindProperty]
  public CreateOrganisationViewModel Organisation { get; set; } = null!;

  public IActionResult OnGet()
  {
    Organisation = new CreateOrganisationViewModel();
    return Page();
  }

  public async Task<IActionResult> OnPostAsync()
  {
    if (!ModelState.IsValid)
    {
      return Page();
    }

    var result = await mediator.Send(new CreateOrganisationCommand(Organisation.Name)).ConfigureAwait(false);

    AddResultMessages(result);

    if (!result.IsSuccess)
    {
      return Page();
    }

    return RedirectToPageWithSuccessMessage("List", $"Organisation '{Organisation.Name}' is created");
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/CreateTeam.cshtml.cs
using GoalManager.UseCases.Organisation.AddTeam;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;

namespace GoalManager.Web.Pages.Organisation;

[Authorize]
public class CreateTeamModel(IMediator mediator) : PageModelBase
{
  [Required]
  [BindProperty]
  public string TeamName { get; set; } = null!;

  public async Task<IActionResult> OnPostAsync(int organisationId)
  {
    if (!ModelState.IsValid)
    {
      return Page();
    }

    var result = await mediator.Send(new AddTeamCommand(organisationId, TeamName)).ConfigureAwait(false); 
    
    AddResultMessages(result);

    if (!result.IsSuccess)
    {
      return Page();
    }

    return RedirectToPageWithSuccessMessage("Update", new { id = organisationId }, $"Team '{TeamName}' is created");
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/List.cshtml.cs
using GoalManager.UseCases.Organisation.DeleteOrganisation;
using GoalManager.UseCases.Organisation.ListOrganisations;
using GoalManager.Web.Common;
using GoalManager.Web.ViewModels.Organisation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.Organisation;

[Authorize]
public class ListModel(IMediator mediator) : PageModelBase
{
  public IList<OrganisationListItemViewModel> Organisations { get; private set; } = new List<OrganisationListItemViewModel>();

  public async Task OnGetAsync(CancellationToken cancellationToken = default)
  {
    var result = await mediator.Send(new ListOrganisationsQuery(null, null), cancellationToken).ConfigureAwait(false);

    AddResultMessages(result);

    if (result.IsSuccess)
    {
      Organisations = result.Value.Select(x => new OrganisationListItemViewModel(x.Id, x.Name, x.TeamsCount)).ToList();
    }
  }

  public async Task<IActionResult> OnPostDeleteAsync(int id)
  {
    var result = await mediator.Send(new DeleteOrganisationCommand(id)).ConfigureAwait(false);

    AddResultMessages(result);

    await OnGetAsync().ConfigureAwait(false);

    return Page();
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/Update.cshtml.cs
using GoalManager.UseCases.Organisation.DeleteTeam;
using GoalManager.UseCases.Organisation.GetForUpdate;
using GoalManager.UseCases.Organisation.UpdateOrganisations;
using GoalManager.Web.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.Organisation;

[Authorize]
public class UpdateModel(IMediator mediator) : PageModelBase
{
  [BindProperty]
  public OrganisationForUpdateDto? Organisation { get; set; }

  public async Task<IActionResult> OnGetAsync(int id)
  {
    var result = await mediator.Send(new GetOrganisationForUpdateQuery(id)).ConfigureAwait(false);

    AddResultMessages(result);

    if (result.IsSuccess)
    {
      Organisation = result.Value;
    }

    return Page();
  }

  public async Task<IActionResult> OnPostAsync(int id)
  {
    if (!ModelState.IsValid || Organisation == null)
    {
      return await OnGetAsync(id).ConfigureAwait(false);
    }

    var result = await mediator.Send(new UpdateOrganisationCommand(id, Organisation.OrganisationName)).ConfigureAwait(false);

    AddResultMessages(result);

    if (!result.IsSuccess)
    {
      return await OnGetAsync(id).ConfigureAwait(false);
    }

    AddSuccessMessage("Organisation is updated");

    return await OnGetAsync(id).ConfigureAwait(false);
  }

  public async Task<IActionResult> OnPostDeleteTeamAsync(int organisationId, int teamId)
  {
    ModelState.Clear();

    var result = await mediator.Send(new DeleteTeamCommand(organisationId, teamId)).ConfigureAwait(false);

    AddResultMessages(result);

    await OnGetAsync(organisationId).ConfigureAwait(false);

    return Page();
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/UpdateTeam.cshtml.cs
using GoalManager.UseCases.Organisation.GetTeamForUpdate;
using GoalManager.UseCases.Organisation.RemoveTeamMember;
using GoalManager.UseCases.Organisation.UpdateTeam;
using GoalManager.Web.Common;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.Organisation;

[Authorize]
public class UpdateTeamModel(IMediator mediator) : PageModelBase
{
  [BindProperty]
  public string TeamName { get; set; } = null!;

  public TeamForUpdateDto? Team { get; set; }

  public async Task<IActionResult> OnGetAsync(int teamId)
  {
    var result = await mediator.Send(new GetTeamForUpdateQuery(teamId)).ConfigureAwait(false);

    AddResultMessages(result);

    if (result.IsSuccess)
    {
      Team = result.Value;
      TeamName = result.Value.Name;
    }

    return Page();
  }

  public async Task<IActionResult> OnPostAsync(int organisationId, int teamId)
  {
    if (!ModelState.IsValid || string.IsNullOrWhiteSpace(TeamName))
    {
      return await OnGetAsync(teamId).ConfigureAwait(false);
    }

    var result = await mediator.Send(new UpdateTeamCommand(organisationId, teamId, TeamName)).ConfigureAwait(false);

    AddResultMessages(result);

    if (!result.IsSuccess)
    {
      return await OnGetAsync(teamId).ConfigureAwait(false);
    }

    AddSuccessMessage("Team is updated");

    return await OnGetAsync(teamId).ConfigureAwait(false);
  }

  public async Task<IActionResult> OnPostRemoveMemberAsync(int organisationId, int teamId, int userId)
  {
    ModelState.Clear();

    var result = await mediator.Send(new RemoveTeamMemberCommand(organisationId, teamId, userId)).ConfigureAwait(false);

    AddResultMessages(result);

    await OnGetAsync(organisationId).ConfigureAwait(false);

    return Page();
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/PerformanceEvaluation/List.cshtml.cs
using GoalManager.UseCases.GoalManagement.GetTeamGoalSetListsOfTeamLeader;
using GoalManager.UseCases.PerformanceEvaluation.CalculatePerformanceEvaluation;
using GoalManager.Web.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoalManager.Web.Pages.PerformanceEvaluation;

[Authorize]
public class ListModel(IMediator mediator) : PageModelBase
{
  public List<TeamGoalSetListItem>? Items { get; private set; }

  public async Task<IActionResult> OnGetAsync(CancellationToken cancellationToken = default)
  {
    var user = HttpContext.GetUserContext();
    var result = await mediator.Send(new GetTeamGoalSetListsOfTeamLeaderQuery(user.Id), cancellationToken).ConfigureAwait(false);
    
    AddResultMessages(result);

    Items = result.IsSuccess ? result.Value : [];

    return Page();
  }

  public async Task<IActionResult> OnPostCalculateEvaluationAsync(int teamId, CancellationToken cancellationToken = default)
  {
    var result = await mediator.Send(new CalculatePerformanceEvaluationCommand(teamId), cancellationToken).ConfigureAwait(false);
    
    AddResultMessages(result);

    return await OnGetAsync(cancellationToken).ConfigureAwait(false);
  }
}

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/AddMember.cshtml
@page "AddMember/{organisationId:int}/{teamId:int}"
@model GoalManager.Web.Pages.Organisation.AddMemberModel
@{
	ViewData["Title"] = "Add Team Member";
}

<div class="container py-4">
	<div class="text-center mb-5">
		<h1 class="h3 fw-light mb-2">Add Team Member</h1>
		<p class="text-muted">Add a new member to @Model.TeamName</p>
	</div>

	<alert-messages error-messages="Model.ErrorMessages" success-messages="Model.SuccessMessages"></alert-messages>

	<div class="card border-0 shadow-sm mx-auto" style="max-width: 600px;">
		<div class="card-body p-4 p-md-5">
			<form method="post">
				<div asp-validation-summary="ModelOnly" class="alert alert-danger mb-4"></div>

				<div class="mb-4">
					<label class="form-label small text-muted">Team</label>
					<div class="form-control bg-light bg-opacity-50">
						@Model.TeamName
					</div>
					<input type="hidden" asp-for="TeamName" />
				</div>

				<div class="mb-4">
					<label asp-for="UserId" class="form-label small text-muted">Select User</label>
					<select asp-for="UserId" asp-items="Model.Users" class="form-control form-select">
						<option value="">Select a user</option>
					</select>
					<span asp-validation-for="UserId" class="text-danger small"></span>
				</div>

				<div class="mb-4">
					<label asp-for="MemberTypeId" class="form-label small text-muted">Member Type</label>
					<select asp-for="MemberTypeId" asp-items="Model.MemberTypes" class="form-control form-select">
						<option value="">Select member type</option>
					</select>
					<span asp-validation-for="MemberTypeId" class="text-danger small"></span>
				</div>

				<div class="mt-4 pt-3 border-top d-flex justify-content-between">
					<button type="submit" class="btn btn-primary px-4">
						<i class="fas fa-user-plus me-2"></i>Add Member
					</button>
					<a asp-page="UpdateTeam"
					   asp-route-organisationId="@RouteData.Values["organisationId"]"
					   asp-route-teamId="@RouteData.Values["teamId"]"
					   class="btn btn-outline-secondary">
						Cancel
					</a>
				</div>
			</form>
		</div>
	</div>
</div>

<style>
	.form-control, .form-select {
		border-radius: 0.25rem;
		border: 1px solid #dee2e6;
	}

		.form-control:focus, .form-select:focus {
			border-color: #86b7fe;
			box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
		}

	.card {
		border-radius: 0.5rem;
	}

	.form-select {
		background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='%23666' viewBox='0 0 16 16'%3E%3Cpath d='M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z'/%3E%3C/svg%3E");
		background-repeat: no-repeat;
		background-position: right 0.75rem center;
		background-size: 16px 12px;
	}
</style>

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/List.cshtml
@page
@model GoalManager.Web.Pages.Organisation.ListModel
@{
	ViewData["Title"] = "Organizations";
}

<div class="container py-4">
	<div class="d-flex justify-content-between align-items-center mb-4">
		<div>
			<h1 class="h3 fw-light mb-0">Organizations</h1>
		</div>
		<a asp-page="Create" class="btn btn-primary">
			<i class="fas fa-plus me-1"></i> New Organization
		</a>
	</div>

	<alert-messages error-messages="Model.ErrorMessages" success-messages="Model.SuccessMessages"></alert-messages>

	@if (Model.Organisations.Count == 0)
	{
		<div class="card border-0 shadow-sm text-center py-5">
			<i class="fas fa-building fa-3x text-muted mb-3"></i>
			<h3 class="h5 fw-normal">No organizations</h3>
			<p class="text-muted mb-4">Get started by creating your first organization</p>
			<a asp-page="Create" class="btn btn-primary px-4">
				<i class="fas fa-plus me-1"></i> Create Organization
			</a>
		</div>
	}
	else
	{
		<div class="card border-0 shadow-sm">
			<div class="table-responsive">
				<table class="table table-hover mb-0">
					<thead class="bg-light">
						<tr>
							<th class="border-0">#</th>
							<th class="border-0">Name</th>
							<th class="border-0">Teams</th>
							<th class="border-0 text-end"></th>
						</tr>
					</thead>
					<tbody>
						@foreach (var org in Model.Organisations)
						{
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div>
											<div>@org.Id</div>
										</div>
									</div>
								</td>
								<td>
									<div class="d-flex align-items-center">
										<div>
											<div>@org.Name</div>
										</div>
									</div>
								</td>
								<td>
									<span class="badge bg-light text-dark">@org.TeamsCount</span>
								</td>
								<td class="text-end">
									<div class="d-flex justify-content-end gap-2">
										<a asp-page="Update" asp-route-id="@org.Id" class="btn btn-sm btn-outline-primary">
											<i class="fas fa-edit"></i>
										</a>
										<form asp-page-handler="Delete" asp-route-id="@org.Id" method="post">
											<button type="submit" class="btn btn-sm btn-outline-danger"
													onclick="return confirm('Are you sure you want to delete this organization?')">
												<i class="fas fa-trash-alt"></i>
											</button>
										</form>
									</div>
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	}
</div>

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/Update.cshtml
@page "{id:int}"
@model GoalManager.Web.Pages.Organisation.UpdateModel
@{
	ViewData["Title"] = "Update Organization";
}

<div class="container py-4">
	<div class="text-center mb-5">
		<h1 class="h3 fw-light mb-2">Update Organization</h1>
		<p class="text-muted">Manage organization details and teams</p>
	</div>

	<alert-messages error-messages="Model.ErrorMessages" success-messages="Model.SuccessMessages"></alert-messages>

	@if (Model.Organisation != null)
	{
		<!-- Organization Update Form -->
		<div class="card border-0 shadow-sm mb-4">
			<div class="card-body p-4 p-md-5">
				<form method="post">
					<div asp-validation-summary="ModelOnly" class="alert alert-danger mb-4"></div>

					<div class="mb-4">
						<label asp-for="@Model.Organisation.OrganisationName" class="form-label small text-muted">Organization Name</label>
						<input asp-for="@Model.Organisation.OrganisationName" class="form-control" placeholder="Enter organization name" />
						<span asp-validation-for="@Model.Organisation.OrganisationName" class="text-danger small"></span>
					</div>

					<div class="mt-4 pt-3 border-top d-flex justify-content-between">
						<button type="submit" class="btn btn-primary px-4">
							<i class="fas fa-save me-2"></i>Update Organization
						</button>
						<a asp-page="List" class="btn btn-outline-secondary">
							Cancel
						</a>
					</div>
				</form>
			</div>
		</div>

		<!-- Teams Section -->
		<div class="d-flex justify-content-between align-items-center mb-3">
			<h2 class="h4 fw-light">Teams</h2>
			<a asp-page="CreateTeam" asp-route-organisationId="@Model.Organisation.Id" class="btn btn-primary">
				<i class="fas fa-plus me-2"></i>Create Team
			</a>
		</div>

		@if (Model.Organisation.Teams.Count == 0)
		{
			<div class="card border-0 shadow-sm text-center py-5">
				<i class="fas fa-users fa-3x text-muted mb-3"></i>
				<h3 class="h5 fw-normal">No teams created</h3>
				<p class="text-muted">Get started by creating your first team</p>
			</div>
		}
		else
		{
			<div class="card border-0 shadow-sm">
				<div class="table-responsive">
					<table class="table table-hover mb-0">
						<thead class="bg-light">
							<tr>
								<th class="border-0">#</th>
								<th class="border-0">Name</th>
								<th class="border-0">Members</th>
								<th class="border-0 text-end"></th>
							</tr>
						</thead>
						<tbody>
							@foreach (var team in Model.Organisation.Teams)
							{
								<tr>
									<td>
										<div class="d-flex align-items-center">
											<div>
												<div>@team.Id</div>
											</div>
										</div>
									</td>
									<td>
										<div class="d-flex align-items-center">
											<div>
												<div>@team.Name</div>
											</div>
										</div>
									</td>
									<td>
										<span class="badge bg-light text-dark">@team.MemberCount</span>
									</td>
									<td class="text-end">
										<div class="d-flex justify-content-end gap-2">
											<a asp-page="UpdateTeam"
											   asp-route-organisationId="@Model.Organisation.Id"
											   asp-route-teamId="@team.Id"
											   class="btn btn-sm btn-outline-primary">
												<i class="fas fa-edit"></i>
											</a>
											<form asp-page-handler="DeleteTeam"
												  asp-route-teamId="@team.Id"
												  asp-route-organisationId="@Model.Organisation.Id"
												  method="post">
												<button type="submit"
														class="btn btn-sm btn-outline-danger"
														onclick="return confirm('Are you sure you want to delete this team?')">
													<i class="fas fa-trash-alt"></i>
												</button>
											</form>
										</div>
									</td>
								</tr>
							}
						</tbody>
					</table>
				</div>
			</div>
		}
	}
</div>

<style>
	.form-control, .form-select {
		border-radius: 0.25rem;
		border: 1px solid #dee2e6;
	}

		.form-control:focus, .form-select:focus {
			border-color: #86b7fe;
			box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
		}

	.card {
		border-radius: 0.5rem;
	}

	.table-hover tbody tr:hover {
		background-color: rgba(0, 0, 0, 0.02);
	}
</style>

ddd/goal-management-system/src/GoalManager.Web/Pages/Organisation/UpdateTeam.cshtml
@page "{organisationId:int}/{teamId:int}"
@model GoalManager.Web.Pages.Organisation.UpdateTeamModel
@{
	ViewData["Title"] = "Update Team";
}

<div class="container py-4">
	<div class="text-center mb-5">
		<h1 class="h3 fw-light mb-2">Update Team</h1>
		<p class="text-muted">Manage team details and members</p>
	</div>

	<alert-messages error-messages="Model.ErrorMessages" success-messages="Model.SuccessMessages"></alert-messages>

	@if (Model.Team != null)
	{
		<div class="card border-0 shadow-sm mb-4">
			<div class="card-body p-4 p-md-5">
				<form method="post">
					<div asp-validation-summary="ModelOnly" class="alert alert-danger mb-4"></div>

					<div class="mb-4">
						<label asp-for="TeamName" class="form-label small text-muted">Team Name</label>
						<input asp-for="TeamName" class="form-control" placeholder="Enter team name" />
						<span asp-validation-for="TeamName" class="text-danger small"></span>
					</div>

					<div class="mt-4 pt-3 border-top d-flex justify-content-between">
						<button type="submit" class="btn btn-primary px-4">
							<i class="fas fa-save me-2"></i>Update Team
						</button>
						<a asp-page="Update" asp-route-id="@RouteData.Values["organisationId"]" class="btn btn-outline-secondary">
							Cancel
						</a>
					</div>
				</form>
			</div>
		</div>

		<div class="d-flex justify-content-between align-items-center mb-3">
			<h2 class="h4 fw-light">Team Members</h2>
			<div>
				<a asp-page="AddMember"
				   asp-route-organisationId="@RouteData.Values["organisationId"]"
				   asp-route-teamId="@Model.Team.Id"
				   class="btn btn-primary me-2">
					<i class="fas fa-user-plus me-2"></i>Add Member
				</a>
				<a asp-page="/GoalManagement/AddGoalPeriod"
				   asp-route-teamid="@Model.Team.Id"
				   class="btn btn-outline-primary">
					<i class="fas fa-calendar-plus me-2"></i>Create Goal Period
				</a>
			</div>
		</div>

		@if (!Model.Team.TeamMembers.Any())
		{
			<div class="card border-0 shadow-sm text-center py-5">
				<i class="fas fa-users fa-3x text-muted mb-3"></i>
				<h3 class="h5 fw-normal">No team members</h3>
				<p class="text-muted">Add members to get started</p>
			</div>
		}
		else
		{
			<div class="card border-0 shadow-sm">
				<div class="table-responsive">
					<table class="table table-hover mb-0">
						<thead class="bg-light">
							<tr>
								<th class="border-0">#</th>
								<th class="border-0">Member</th>
								<th class="border-0">Type</th>
								<th class="border-0 text-end"></th>
							</tr>
						</thead>
						<tbody>
							@foreach (var member in Model.Team.TeamMembers)
							{
								<tr>
									<td>
										<div class="d-flex align-items-center">
											<div>
												<div>@member.Id</div>
											</div>
										</div>
									</td>
									<td>
										<div class="d-flex align-items-center">
											<div>
												<div>@member.Name</div>
											</div>
										</div>
									</td>
									<td>
										<span class="badge bg-light text-dark">@member.MemberType</span>
									</td>
									<td class="text-end">
										<form asp-page-handler="RemoveMember"
											  asp-route-userid="@member.UserId"
											  method="post">
											<button type="submit"
													class="btn btn-sm btn-outline-danger"
													onclick="return confirm('Are you sure you want to remove this member?')">
												<i class="fas fa-trash-alt"></i>
											</button>
										</form>
									</td>
								</tr>
							}
						</tbody>
					</table>
				</div>
			</div>
		}
	}
</div>

<style>
	.form-control, .form-select {
		border-radius: 0.25rem;
		border: 1px solid #dee2e6;
	}

		.form-control:focus, .form-select:focus {
			border-color: #86b7fe;
			box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
		}

	.card {
		border-radius: 0.5rem;
	}

	.table-hover tbody tr:hover {
		background-color: rgba(0, 0, 0, 0.02);
	}

	.badge {
		padding: 0.35em 0.65em;
		font-weight: 500;
	}
</style>